<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentAssertions" Version="7.2.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
      <PackageReference Include="Moq" Version="4.7.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SFA.DAS.RAA.Vacancy.AI.Api\SFA.DAS.RAA.Vacancy.AI.Api.csproj" />
    </ItemGroup>

</Project>
